kind: Service
apiVersion: v1
metadata:
  name: namespace1
  namespace: dex1
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  namespace1
      prefix: /
      service:  namespace1.dex1
      host: dexpoc1.savvybi.io
spec:
  type: NodePort
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80