---
apiVersion: v1
kind: Service
metadata:
  name:  druid-middlemanager-service
  labels:
    k8s-app: druid-middlemanager-service
spec:
  type: NodePort
  ports:
    - name: middlemanager-port
      port: 8091
    - name: peon-0
      port: 8100
    - name: peon-1
      port: 8101
    - name: peon-2
      port: 8102
    - name: peon-3
      port: 8103
  selector:
    k8s-app: druid-middlemanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: druid-middlemanager
spec:
  serviceName: druid-middlemanager-service
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: druid-middlemanager
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: druid-middlemanager
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-middlemanager:0.1
        imagePullPolicy: IfNotPresent
        ports:
          - port: 8091
          - port: 8100
          - port: 8101
          - port: 8102
          - port: 8103
