kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: superset
  name: superset
  annotations:
    external-dns.alpha.kubernetes.io/hostname: superset-app.superset.savvybi.enterprises
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:547051082101:certificate/db421ea7-2bb1-4e29-a9cc-5fcd9937b752
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: backend-http
    - name: http
      protocol: TCP
      port: 80
      targetPort: backend-http
  selector:
    k8s-app: superset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  selector:
    matchLabels:
      k8s-app: superset
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: superset
    spec:
      containers:
        - name: superset
          image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/superset-app:0.1-dev
          ports:
          - containerPort: 8088
            name: backend-http
