---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: superset
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      k8s-app: superset
  template: 
    metadata: 
      labels: 
        k8s-app: superset
    spec: 
      containers: 
        - 
          image: $REPOSITORY_URI
          imagePullPolicy: Always
          name: superset
          ports: 
            - 
              containerPort: 8088
              name: backend-http
