kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: superset
  name: superset
  annotations:
    external-dns.alpha.kubernetes.io/hostname: demo-app.aws2-vpc-ss-dts.savvybi.enterprises
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:547051082101:certificate/fa23783c-1f05-4dc2-bc78-72731ff4f7ce
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: backend-http
    - name: http
      protocol: TCP
      port: 80
      targetPort: backend-http
  selector:
    k8s-app: superset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  selector:
    matchLabels:
      k8s-app: superset
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: superset
    spec:
      containers:
        - name: superset
          imagePullPolicy: Always
          image: 547051082101.dkr.ecr.us-west-2.amazonaws.com/zawee/superset-app:production
          ports:
          - containerPort: 8088
            name: backend-http
