# kind: Service
# apiVersion: v1
# metadata:
#   labels:
#     k8s-app: superset
#   name: superset
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: backend-http
#   selector:
#     k8s-app: superset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  selector:
    matchLabels:
      k8s-app: superset
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: superset
    spec:
      containers:
        - name: superset
          imagePullPolicy: Always
          image: $REPOSITORY_URI:$TAG
        - containerPort: 8088
          name: backend-http
