apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-broker-deployment
  labels:
    k8s-app: druid-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: druid-broker
  template:
    metadata:
      labels:
        k8s-app: druid-broker
    spec:
      hostname: druid-broker
      containers:
      - name: druid-broker
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-broker:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: druid-broker
  labels:
    k8s-app: druid-broker
spec:
  ports:
  - name: druid-broker-port
    port: 8082
  selector:
    k8s-app: druid-broker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-coordinator-deployment
  labels:
    k8s-app: druid-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: druid-coordinator
  template:
    metadata:
      labels:
        k8s-app: druid-coordinator
    spec:
      hostname: druid-coordinator
      containers:
      - name: druid-coordinator
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-coordinator:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator
  labels:
    k8s-app: druid-coordinator
spec:
  ports:
  - name: druid-coordinator-port
    port: 8081
  selector:
    k8s-app: druid-coordinator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-historical-deployment
  labels:
    k8s-app: druid-historical
spec:
  selector:
    matchLabels:
      k8s-app: druid-historical
  replicas: 1
  template:
    metadata:
      labels:
        name: druid-historical-rc
        k8s-app: druid-historical
    spec:
      containers:
      - name: druid-historical
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-historical:0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8083
        #TODO add readiness & liveness probes
        volumeMounts:
          - name: data
            mountPath: /var/druid/segments
          - name: segment-cache
            mountPath: /var/druid/segment-cache
      #    - name: config-volume
      #      mountPath: "/{{ .Values.iapVersion }}/conf/druid/"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: druid-deep-storage
      - name: segment-cache
        persistentVolumeClaim:
          claimName: druid-deep-segment-cache
      #- name: config-volume
      #  configMap:
      #    name: common-runtime-configmap
      #    items:
      #      - key: common.runtime.properties
      #        path: _common/common.runtime.properties
      #      - key: "{{ .Values.nodes.historical.name }}.runtime.properties"
      #        path: historical/runtime.properties
      #      - key: "{{ .Values.nodes.historical.name }}.jvm.config"
      #        path: historical/jvm.config
      #      - key: "{{ .Values.nodes.historical.name }}.main.config"
      #        path: historical/main.config

---
apiVersion: v1
kind: Service
metadata:
  name: druid-historical
  #TODO flexible service Name, configMap
  labels:
    k8s-app: druid-historical
spec:
  type: ClusterIP
  ports:
  - name: druid-historical-port
    port: 8083
  selector:
    k8s-app: druid-historical

---
apiVersion: v1
kind: Service
metadata:
  name:  druid-middlemanager-service
  labels:
    k8s-app: druid-middlemanager-service
spec:
  type: NodePort
  ports:
    - name: middlemanager-port
      port: 8091
    - name: peon-0
      port: 8100
    - name: peon-1
      port: 8101
    - name: peon-2
      port: 8102
    - name: peon-3
      port: 8103
  selector:
    k8s-app: druid-middlemanager

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: druid-middlemanager
spec:
  selector:
    matchLabels:
      k8s-app: druid-middlemanager
  serviceName: druid-middlemanager-service
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: druid-middlemanager
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: druid-middlemanager
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-middlemanager:0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8091
          - containerPort: 8100
          - containerPort: 8101
          - containerPort: 8102
          - containerPort: 8103
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/druid/conf"
      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: middleManager.runtime.properties
              path: middleManager/runtime.properties
            - key: middleManager.jvm.config
              path: middleManager/jvm.config
            - key: middleManager.main.config
              path: middleManager/main.config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-overlord-deployment
  labels:
    k8s-app: druid-overlord
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: druid-overlord
  template:
    metadata:
      labels:
        k8s-app: druid-overlord
    spec:
      hostname: druid-overlord
      containers:
      - name: druid-overlord
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-overlord:0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: druid-overlord
  labels:
    k8s-app: druid-overlord-service
spec:
  type: NodePort
  ports:
  - name: druid-overlord-port
    port: 8090
  - name: https
    protocol: TCP
    port: 443
    targetPort: overlord-port
  - name: http
    protocol: TCP
    port: 80
    targetPort: overlord-port
  selector:
      k8s-app: druid-overlord
