apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-coordinator-deployment
  labels:
    k8s-app: druid-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: druid-coordinator
  template:
    metadata:
      labels:
        k8s-app: druid-coordinator
    spec:
      hostname: druid-coordinator
      containers:
      - name: druid-coordinator
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-coordinator:0.1
        ports:
          - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator
  labels:
    k8s-app: druid-coordinator
spec:
  type: NodePort
  ports:
  - name: coordinator-port
    port: 8081
  selector:
    matchLabels:
      k8s-app: druid-coordinator
