FROM 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-base:0.1
MAINTAINER foamdino@gmail.com

EXPOSE 8090

WORKDIR /opt/druid
ENTRYPOINT cd /opt/druid && /opt/druid/bin/run.sh overlord
