apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-overlord-deployment
  labels:
    k8s-app: druid-overlord
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: druid-overlord
  template:
    metadata:
      labels:
        k8s-app: druid-overlord
    spec:
      hostname: druid-overlord
      containers:
      - name: druid-overlord
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-overlord:0.1
        pullPolicy: IfNotPresent
        ports:
          - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: druid-overlord
  labels:
    k8s-app: druid-overlord-service
spec:
  type: NodePort
  ports:
  - name: druid-overlord-port
    port: 8090
  selector:
    matchLabels:
      k8s-app: druid-overlord
